channels:
  - conda-forge
  - bioconda

dependencies:
  - conda-forge::pip=25.2
  - conda-forge::python=3.13.7
  - pip:
      - SigProfilerAssignment==0.2.6
      - SigProfilerExtractor==1.2.2
      - SigProfilerMatrixGenerator==1.3.5
      - pandas==2.3.2
      - sigProfilerPlotting==1.4.1
