---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::trycycler=0.5.3
  - conda-forge::python=3.9.7
  - conda-forge::setuptools=59.4
