---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::mapdamage2=2.2.1
  - conda-forge::python=3.7.6
  - conda-forge::setuptools=47.1
